import portfolioHome from './Designer.svg';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={portfolioHome} className="Portfolio-image" alt="Woman holding a grey cat"/>
        <p>Image generated by Microsoft Designer AI</p>
      </header>
    </div>
  );
}

export default App;
